CREATE CONSTRAINT region_id_unique IF NOT EXISTS FOR (r:Region) REQUIRE r.id IS UNIQUE;
CREATE CONSTRAINT site_id_unique IF NOT EXISTS FOR (s:Site) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT cell_id_unique IF NOT EXISTS FOR (c:Cell) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT sector_id_unique IF NOT EXISTS FOR (t:Sector) REQUIRE t.id IS UNIQUE;
CREATE CONSTRAINT alarm_id_unique IF NOT EXISTS FOR (a:Alarm) REQUIRE a.id IS UNIQUE;
CREATE CONSTRAINT kpi_id_unique IF NOT EXISTS FOR (k:KPI) REQUIRE k.id IS UNIQUE;
CREATE CONSTRAINT weather_id_unique IF NOT EXISTS FOR (w:Weather) REQUIRE w.id IS UNIQUE;

CREATE INDEX region_name IF NOT EXISTS FOR (r:Region) ON (r.name);
CREATE INDEX site_name IF NOT EXISTS FOR (s:Site) ON (s.name);
CREATE INDEX cell_name IF NOT EXISTS FOR (c:Cell) ON (c.name);
CREATE INDEX alarm_severity IF NOT EXISTS FOR (a:Alarm) ON (a.severity);
