from __future__ import annotations

from app.synthetic_data.generators.telecom_base import TelecomBaseGenerator
from app.synthetic_data.models.telecom.carrier import Carrier
from app.synthetic_data.models.telecom.enums import CarrierName


class CarrierGenerator(TelecomBaseGenerator[Carrier]):
    """Generate Carrier domain objects."""

    async def generate_one(self, scenario: object | None = None) -> Carrier:
        return Carrier(
            name=self._faker.random_element(elements=list(CarrierName)),
            code=self._faker.bothify(text="CAR-####"),
            description=f"Carrier generated by {self.__class__.__name__}",
        )
