from __future__ import annotations

from app.synthetic_data.generators.telecom_base import TelecomBaseGenerator
from app.synthetic_data.models.telecom.circle import Circle


class CircleGenerator(TelecomBaseGenerator[Circle]):
    """Generate Circle domain objects."""

    async def generate_one(self, scenario: object | None = None, region_id: str | None = None) -> Circle:
        return Circle(
            name=self._faker.city_suffix(),
            code=self._faker.bothify(text="CIR-####"),
            region_id=region_id or "region-id",
            description=f"Circle generated by {self.__class__.__name__}",
        )
