from __future__ import annotations

from app.synthetic_data.generators.telecom_base import TelecomBaseGenerator
from app.synthetic_data.models.telecom.cluster import Cluster


class ClusterGenerator(TelecomBaseGenerator[Cluster]):
    """Generate Cluster domain objects."""

    async def generate_one(self, scenario: object | None = None, market_id: str | None = None) -> Cluster:
        return Cluster(
            name=self._faker.word().capitalize(),
            code=self._faker.bothify(text="CL-####"),
            market_id=market_id or "market-id",
            description=f"Cluster generated by {self.__class__.__name__}",
        )
