from __future__ import annotations

from app.synthetic_data.generators.telecom_base import TelecomBaseGenerator
from app.synthetic_data.models.telecom.market import Market


class MarketGenerator(TelecomBaseGenerator[Market]):
    """Generate Market domain objects."""

    async def generate_one(self, scenario: object | None = None, circle_id: str | None = None) -> Market:
        return Market(
            name=self._faker.city(),
            code=self._faker.bothify(text="MKT-####"),
            circle_id=circle_id or "circle-id",
            description=f"Market generated by {self.__class__.__name__}",
        )
