from __future__ import annotations

from app.synthetic_data.generators.telecom_base import TelecomBaseGenerator
from app.synthetic_data.models.telecom.region import Region


class RegionGenerator(TelecomBaseGenerator[Region]):
    """Generate Region domain objects."""

    async def generate_one(self, scenario: object | None = None) -> Region:
        return Region(
            name=self._faker.state(),
            code=self._faker.bothify(text="REG-####"),
            description=f"Region generated by {self.__class__.__name__}",
        )
