from __future__ import annotations

from typing import Any, Protocol


class Connector(Protocol):
    async def initialize(self) -> dict[str, Any]: ...
    async def start(self) -> dict[str, Any]: ...
    async def stop(self) -> dict[str, Any]: ...
    async def restart(self) -> dict[str, Any]: ...
    async def reconnect(self) -> dict[str, Any]: ...
    async def heartbeat(self) -> dict[str, Any]: ...
    async def health_check(self) -> dict[str, Any]: ...
    async def get_status(self) -> dict[str, Any]: ...


class StreamingConnector(Protocol):
    async def stream_messages(self) -> list[dict[str, Any]]: ...


class PollingConnector(Protocol):
    async def poll(self) -> list[dict[str, Any]]: ...


class MessageConnector(Protocol):
    async def publish_message(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def consume_messages(self) -> list[dict[str, Any]]: ...


class ApiConnector(Protocol):
    async def request(self, method: str, path: str, payload: dict[str, Any] | None = None) -> dict[str, Any]: ...


class DatabaseConnector(Protocol):
    async def query(self, statement: str) -> list[dict[str, Any]]: ...


class FileConnector(Protocol):
    async def read_file(self, path: str) -> str: ...
    async def write_file(self, path: str, content: str) -> dict[str, Any]: ...


class CloudConnector(Protocol):
    async def invoke(self, payload: dict[str, Any]) -> dict[str, Any]: ...


class TelemetryConnector(Protocol):
    async def pull_telemetry(self) -> list[dict[str, Any]]: ...


class InventoryConnector(Protocol):
    async def sync_inventory(self) -> list[dict[str, Any]]: ...


class TicketConnector(Protocol):
    async def sync_tickets(self) -> list[dict[str, Any]]: ...


class EventConnector(Protocol):
    async def emit_event(self, payload: dict[str, Any]) -> dict[str, Any]: ...


class HealthCheck(Protocol):
    async def health_check(self) -> dict[str, Any]: ...


class AuthenticationProvider(Protocol):
    async def authenticate(self, configuration: dict[str, Any]) -> dict[str, str]: ...


class AuthorizationProvider(Protocol):
    async def authorize(self, action: str, principal: str, scopes: list[str]) -> bool: ...


class SchemaProvider(Protocol):
    async def get_schema(self, schema_name: str) -> dict[str, Any]: ...


class MetadataProvider(Protocol):
    async def get_metadata(self) -> dict[str, Any]: ...


class CapabilityProvider(Protocol):
    async def get_capabilities(self) -> list[str]: ...


class DiscoveryProvider(Protocol):
    async def discover(self) -> dict[str, Any]: ...


class Lifecycle(Protocol):
    async def initialize(self) -> dict[str, Any]: ...
    async def start(self) -> dict[str, Any]: ...
    async def stop(self) -> dict[str, Any]: ...
    async def restart(self) -> dict[str, Any]: ...


class ConfigurationProvider(Protocol):
    async def load(self) -> dict[str, Any]: ...


class TransformationProvider(Protocol):
    async def transform(self, payload: dict[str, Any], *, profile: str) -> dict[str, Any]: ...


class Mapper(Protocol):
    async def map_record(self, payload: dict[str, Any]) -> dict[str, Any]: ...


class Validator(Protocol):
    async def validate(self, payload: Any) -> None: ...


class Serializer(Protocol):
    async def serialize(self, payload: Any) -> str: ...


class Deserializer(Protocol):
    async def deserialize(self, payload: str) -> Any: ...


class EventPublisher(Protocol):
    async def publish_event(self, topic: str, payload: dict[str, Any]) -> None: ...


class EventSubscriber(Protocol):
    async def consume_events(self, topic: str) -> list[dict[str, Any]]: ...


class MetricsCollector(Protocol):
    async def record_metric(self, connector_id: str, metric: str, value: float) -> None: ...
    async def get_metrics(self, connector_id: str | None = None) -> dict[str, Any]: ...


class RetryStrategy(Protocol):
    async def execute(self, operation: Any) -> Any: ...


class CacheProvider(Protocol):
    async def get(self, key: str) -> Any: ...
    async def set(self, key: str, value: Any) -> None: ...